a = int(input('Enter Foundation English : '))
b = int(input('Enter General Business : '))
c = int(input('Enter Introduction to Computer Systems :'))
d = int(input('Enter Computer Progarmming : '))
print('--- Your score ---')
print('Foundation English :',a)
print('General Business :',b)
print('Introduction to Computer Systems :',c)
print('Computer Progarmming :',d)
